from typing import Literal

GenderType = Literal[
    "AGENDER",
    "ANDROGYNOUS",
    "BIGENDER",
    "GENDER_FLUID",
    "GENDER_NONCONFORMING",
    "GENDER_QUEER",
    "GENDER_QUESTIONING",
    "INTERSEX",
    "MAN",
    "NON_BINARY",
    "OTHER",
    "PANGENDER",
    "TRANSFEMININE",
    "TRANSMASCULINE",
    "TRANS_PERSON",
    "TRANS_MAN",
    "TRANS_NON_BINARY",
    "TRANS_WOMAN",
    "TRANS_HUMAN",
    "TWO_SPIRIT",
    "WOMAN",
]


### TECHNICALLY Literal is easier and enough ###
# class Gender(Enum):
#     AGENDER = "AGENDER"
#     ANDROGYNOUS = "ANDROGYNOUS"
#     BIGENDER = "BIGENDER"
#     GENDER_FLUID = "GENDER_FLUID"
#     GENDER_NONCONFORMING = "GENDER_NONCONFORMING"
#     GENDERQUEER = "GENDERQUEER"
#     GENDER_QUESTIONING = "GENDER_QUESTIONING"
#     INTERSEX = "INTERSEX"
#     MAN = "MAN"
#     NON_BINARY = "NON_BINARY"
#     OTHER = "OTHER"
#     PANGENDER = "PANGENDER"
#     TRANSFEMININE = "TRANSFEMININE"
#     TRANSMASCULINE = "TRANSMASCULINE"
#     TRANS_PERSON = "TRANS_PERSON"
#     TRANS_MAN = "TRANS_MAN"
#     TRANS_NON_BINARY = "TRANS_NON_BINARY"
#     TRANS_WOMAN = "TRANS_WOMAN"
#     TWO_SPIRIT = "TWO_SPIRIT"
#     WOMAN = "WOMAN"
