from typing import Literal

LookingForType = Literal[
    "MAN",
    "WOMAN",
    "MAN_MAN_COUPLE",
    "MAN_WOMAN_COUPLE",
    "ANDROGYNOUS",
    "BIGENDER",
    "AGENDER",
    "WOMAN_WOMAN_COUPLE",
    "GENDER_FLUID",
    "GENDER_NONCONFORMING",
    "GENDER_QUEER",
    "GENDER_QUESTIONING",
    "INTERSEX",
    "NON_BINARY",
    "PANGENDER",
    "OTHER",
    "TRANSFEMININE",
    "TRANSMASCULINE",
    "TRANS_HUMAN",
    "TRANS_MAN",
    "TRANS_NON_BINARY",
    "TRANS_WOMAN",
    "TWO_SPIRIT",
]
