from typing import Literal

LookingForType = Literal[
    "MAN",
    "WOMAN",
    "MAN_MAN_COUPLE",
    "MAN_WOMAN_COUPLE",
    "ANDROGYNOUS",
    "BIGENDER",
    "AGENDER",
    "WOMAN_WOMAN_COUPLE",
    "GENDER_FLUID",
    "GENDER_NONCONFORMING",
    "GENDER_QUEER",
    "GENDER_QUESTIONING",
    "INTERSEX",
    "NON_BINARY",
    "PANGENDER",
    "OTHER",
    "TRANSFEMININE",
    "TRANSMASCULINE",
    "TRANS_HUMAN",
    "TRANS_MAN",
    "TRANS_NON_BINARY",
    "TRANS_WOMAN",
    "TWO_SPIRIT",
]


### TECHNICALLY Literal is easier and enough ###
# class LookingFor(Enum):
#     MAN = "MAN"
#     WOMAN = "WOMAN"
#     MAN_MAN_COUPLE = "MAN_MAN_COUPLE"
#     MAN_WOMAN_COUPLE = "MAN_WOMAN_COUPLE"
#     ANDROGYNOUS = "ANDROGYNOUS"
#     BIGENDER = "BIGENDER"
#     AGENDER = "AGENDER"
#     WOMAN_WOMAN_COUPLE = "WOMAN_WOMAN_COUPLE"
#     GENDER_FLUID = "GENDER_FLUID"
#     GENDER_NONCONFORMING = "GENDER_NONCONFORMING"
#     GENDER_QUEER = "GENDER_QUEER"
#     GENDER_QUESTIONING = "GENDER_QUESTIONING"
#     INTERSEX = "INTERSEX"
#     NON_BINARY = "NON_BINARY"
#     PANGENDER = "PANGENDER"
#     OTHER = "OTHER"
#     TRANSFEMININE = "TRANSFEMININE"
#     TRANSMASCULINE = "TRANSMASCULINE"
#     TRANS_HUMAN = "TRANS_HUMAN"
#     TRANS_MAN = "TRANS_MAN"
#     TRANS_NON_BINARY = "TRANS_NON_BINARY"
#     TRANS_WOMAN = "TRANS_WOMAN"
#     TWO_SPIRIT = "TWO_SPIRIT"
