from typing import Literal

SexualityType = Literal[
    "ANDROGYNOSEXUAL",
    "ANDROSEXUAL",
    "ASEXUAL",
    "AUTOSEXUAL",
    "BISEXUAL",
    "BI_CURIOUS",
    "DEMISEXUAL",
    "GAY",
    "GRAYA",
    "GYNOSEXUAL",
    "HETEROFLEXIBLE",
    "HOMOFLEXIBLE",
    "LESBIAN",
    "OBJECTUMSEXUAL",
    "OMNISEXUAL",
    "PANSEXUAL",
    "POLYSEXUAL",
    "QUEER",
    "SKOLIOSEXUAL",
    "STRAIGHT",
]


### TECHNICALLY Literal is easier and enough ###
# class Sexuality(Enum):
#     ANDROGYNOSEXUAL = "ANDROGYNOSEXUAL"
#     ANDROSEXUAL = "ANDROSEXUAL"
#     ASEXUAL = "ASEXUAL"
#     AUTOSEXUAL = "AUTOSEXUAL"
#     BISEXUAL = "BISEXUAL"
#     BI_CURIOUS = "BI_CURIOUS"
#     DEMISEXUAL = "DEMISEXUAL"
#     GAY = "GAY"
#     GRAY_A = "GrayA"
#     GYNOSEXUAL = "GYNOSEXUAL"
#     HETEROFLEXIBLE = "HETEROFLEXIBLE"
#     HOMOFLEXIBLE = "HOMOFLEXIBLE"
#     LESBIAN = "LESBIAN"
#     OBJECTUMSEXUAL = "OBJECTUMSEXUAL"
#     OMNISEXUAL = "OMNISEXUAL"
#     PANSEXUAL = "PANSEXUAL"
#     POLYSEXUAL = "POLYSEXUAL"
#     QUEER = "QUEER"
#     SKOLIOSEXUAL = "SKOLIOSEXUAL"
#     STRAIGHT = "STRAIGHT"
